### ISSUE TITLE
UTF-8

### ISSUE THREAD

**Issue by lamduongvan** [akariv/hatool-compiler#1]
Hi Author,

Could you please set UTF-8 is default encoding?

1. f_in.open() -> f_in.open('r', encoding='utf8')
2. f_out.open('w') -> f_out.open('w', encoding='utf8')

Thanks

**Comment by akariv** [comment]
There you go!

If you like, it would be interesting to hear what you're working on...

**Comment by lamduongvan** [comment]
Yes, I'm going to develop chat-bot. Your project is great :)
I need time to upgrade to get more functionality.
